spring:
    # datasource:
    #     url: jdbc:mysql://localhost:3306/spring
    #     username: root
    #     password: root
    #     driver-class-name: com.mysql.jdbc.Driver
    datasource:
        url: jdbc:h2:mem:mydb
        username: sa
        password: password
        driver-class-name: org.h2.Driver